### ISSUE TITLE
nginx config real domain - problem

### ISSUE THREAD

**Issue by webnah** [baealex/BLEX#6]
https://github.com/baealex/BLEX/blob/master/webserver/nginx.conf

please explain for what? port 20204 not use anything in nextjs or django

    server {
        listen 20204;
        listen [::]:20204;

        server_name localhost;

        root /www/static;

        location ~* \.(eof|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        location ~* \.(?:jpg|jpeg|png|gif|ico|gz|svg|svgz|ogg|mp4|webm|ogv|htc|cur)$ {
            expires 3M;
            access_log off;
            add_header Cache-Control "public";
        }
    }

**Comment by baealex** [comment]
The port is a path to provide static files (files registered in `/backend/src/static` and images uploaded by users) through nginx rather than django. I thought that providing static files from django had management and performance problems, so I serve it like this.

**Comment by webnah** [comment]
thank you for your sharing
