### ISSUE TITLE
gmail login success, alive is always death

### ISSUE THREAD

**Issue by webnah** [baealex/BLEX#7]
The result is: user not login, because cookie not set 

login result
![image](https://user-images.githubusercontent.com/46319124/101233826-42280480-36ed-11eb-9106-db8475a8f705.png)

alive
##################################
:method: GET
:scheme: https
:authority: 8ad9bfcff97f.ngrok.io
:path: /v1/alive
Accept: application/json, text/plain, */*
Origin: http://localhost:8002
Accept-Encoding: gzip, deflate, br
Host: 8ad9bfcff97f.ngrok.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8002/
Connection: keep-alive

Response
:status: 200
Access-Control-Allow-Credentials: true
Content-Type: text/html; charset=utf-8
Access-Control-Allow-Origin: http://localhost:8002
Date: Sat, 05 Dec 2020 04:28:01 GMT
X-Frame-Options: SAMEORIGIN
Content-Length: 4
Vary: Origin, Cookie
Server: nginx/1.19.5
##################################
![image](https://user-images.githubusercontent.com/46319124/101233897-b498e480-36ed-11eb-8661-fefb4c5f7836.png)

only set nav logined for first time, if I reload it gone

![image](https://user-images.githubusercontent.com/46319124/101233965-27a25b00-36ee-11eb-9509-a6ac7d42a954.png)

**Comment by webnah** [comment]
it works localhost, not ngrok

**Comment by baealex** [comment]
I leave an answer for someone else who will experience the same problem. Add ngrok domain on backend/src/main/settings.py

- CORS_ALLOWED_ORIGINS
- SESSION_COOKIE_DOMAIN

maybe... it will work!
